>AY700180_Entoloma_prunuloides
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggtagt-c--
----------tttgactgcccgagttgtaatctagagaagtg-ttatccgtgctggacca
tgtacaa-gtctcctggaatggagcgtcatagagggtgagaatcccgtctttgacatgga
c-tg-cc-aggact-ttgtgat-gcgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtca-cgt-tggc-cagggatcaacct--tgct---
--tttc----tgct-tgg-tgtactttctgg-t-tgatgggtcagcatcaa-ttttgacc
aatggagaaaggtc-aggggaatgtggcatc---tt--c----ggatgtg---ttatagc
cc-ttggttgcatac-attggttgggattgagg-aactcagcatg-c---cg-ca-a--g
g-c-cgg-----------------g---taatt-------ttaccacg-ttcatgcttag
gatgctggc---ataatggctttaatcgacccgt
>AY634279_Pluteus_romellii
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcagt-c--
----------tctggctgtccgagttgtaaactagagaagtg-ttatccgtgctggacca
tgtataa-gtctcctggaacggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tc-cc-agtgca-ttgtgat-gcgctctcaaagagtcgagttgtttgggaatgcagct
caaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtcg-cat-tggc-tggggatcaacct--tg-----
--cttt----tgtg-agg-tgtactctctag-t-taatgggtcagcatcaa-ttttgact
gctggaaaaaggtc-aggggaatgtggcatc---tc--a----ggatgtg---ttatagc
cc-ctaatcatatac-agtggttgggattgagg-aactcagcac--c---cg-ta-a--g
g--------------------------------------------------tgtgcttag
gatgctggc---ataatggctttaatcgacccgt
>AF261436_Amanita_armillariiformis
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-gacagt-ctt
t---------tttggctgtccgagttgtaatctagagaagtg-ctatccgtgctggacca
tgtataa-gtctcctgggatggagcatcacagagggtgagaatcccgtctatgacatgga
c-tc-cc-agtgca-ttgtgat-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtca-cat-tggc-tggggatcaaccc--tgct---
--cttt----tgct-ggg-tgtacttcctagtt-tgatgggtcagcatcaa-ttttgatc
actggaaaaaggta-gagggaatgtgacatc---tt--a----ggatgtg--tttatagc
cc-tttattgtatac-agtggttgggattgagg-atctcagcacg-c---cg-ta-a--g
g-c-tgg-----------------gtcat-----------tgaccaca-ctcgtgcttag
gatgctggc---ataatggctttaatcgacccgt
>AY194984_Amanita_nauseosa
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcagt-c-t
t---------tttggctgtccgagttgtaatctagagaagtg-ctatccgtgctggacca
tgtataa-gtctcctgggatggagcatcacagagggtgagaatcccgtctatgacatgga
cttc-cc-agtgca-ttgtgat-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtca-cat-tggc-tggggatcaactc--tgct---
--cttt----tgct-ggg-tgtacttcctag-t-taatgggtcagcatcaa-ttttgatc
actggaaaaaggta-gagggaatgtggcatc---tt--a----ggatgtg---ttatagc
cc-tctattgtatac-agtggttgggattgagg-atatcagcacg-c---cg-ta-a--g
g-c-tgg-----------------gtcat-----------tgaccaca-ctcgtgcttag
gatgctggc---ataatggctttaatcgac----
>GQ250424_Amanita_velosa
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-ctc
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcatcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatactggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcaacct--agctgt-
--tttt----tgct-ggg-tgaatttcctagtc-tgacaggccaacatcag-tcttgact
gctggaaaagagca-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-tttgtcatatgt-gacagttgggactgagg-gatgcagcgtg-c---ca-tg-a--g
g-c-tgg-----------------g---t--ct-------tgaccacg-tacacgcttag
gatgttggc-ttttaatggcttcaatcga-----
>AF024482_Amanita_vaginata
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-ctt
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcgctggacca
tgtataa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcaacct--agctaat
t-tttt----tgct-ggg-tgaatttcctagtc-tgacaggccaacatcag-tcttgact
gctggaaaagagca-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-tttgtcatatgt-ggcagttgggactgagg-gatgcagcatg-c---cg-tg-a--g
g-c-tgg-----------------g---t--ttt------taaccacg-ttcatgcttag
gatgttggc-ttttaatggcttcaatcgacccgt
>AF024461_Amanita_lignitincta
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-ctt
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcgctggacca
tgtataa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcaacct--agct-gt
t-tttt----tgct-ggg-tgaatttcctagtc-tgacaggccaacatcag-tcttgact
gctggaaaagagca-gtgggaatgtggcacc---tt--c----gggtgtg---ttatagc
cc-tttgtcatatgt-ggcagtcgagactgagg-gatgcagcatg-c---cg-tg-a--g
g-c-tgg-----------------g-----------------------------------
----------------------------------
>AF024472_Amanita_pseudovaginata
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-ctt
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcaaccc--agctgt-
--tttt----tgct-ggg-tgaatttcctagtc-tgacaggccaacatcag-tcttgact
gctggaaaagagca-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
ct-tttgtcatatgt-ggcagttgggactgagg-gatgcagcatg-c---cg-tg-a--g
g-c-tgg-----------------g---t--ttc------tgaccacg-ttcatgcttag
gatgttggc-ttttaatggcttcaatc-------
>AF024442_Amanita_brunneofuliginea
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatcc-ggcagt-ctt
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-cg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcaacct--agctgt-
--tttt----tgct-ggg-tgaatttcctagtc-tgacaggccaacatcag-tcttgact
gctggaaaagagca-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
ct-tttgtcatatgt-ggcagttgggactgagg-gatgcagcatg-c---cg-cg-a--g
g-c-tgg-----------------g---t--ttc------tgaccacg-ttcatgctcag
gatgttggc-ttttaatggcttcaatcg------
>GQ250427_Amanita_sp
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-ctt
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcaacct--agctgt-
--tttt----tgct-ggg-tgaatttcctagtc-tgacaggccaacatcag-tcttgact
gctggaaaagagca-gggggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-tttgtcatatgt-ggcagttgggactgagg-gatgcagcatg-c---cg-cg-a--g
g-c-tgg-----------------g---t--ttc------tgaccacg-ttcatgcttag
gatgttggc-ttttaatggcttcaatcgacccgt
>EU522724_Amanita_aff_vaginata
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-cta
ttttttcttctttggctgtccgaattgtaatctagagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcgtcgcagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagttg-tgt-cggc-tagggatcaacct--agctgt-
--tttt----tgct-ggg-tgaatttcctagtc-tgacaggccaacatcag-tcttgact
gctggaaaagagca-gggggaatgtggcacc---tt--t----gggtgtg---ttatagc
ct-tttgtcatatgt-ggcagttgggactgagg-gatgcagcgtg-c---cg-cg-a--g
g-c-tgg-----------------g---t--tt-------cgaccacg-ttcacgcttag
gatgttggc---ttaatggcttcaatcgacccgt
>AF097372_Amanita_ceciliae
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-ctt
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcgctggacca
tgtacaa-gtctcctggaatggagcgtcgcagagggtgagaatcccgtctntgacatgga
c-cg-cc-agcgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-cggc-gagggatcagcct--agct---
--ttgt----cgct-ggg-tgaatttcctggtc-tgacaggccaacatcag-tctcgacc
gctggaaaagagca-gagggaacgtggcacc---tt--c----gggtgtg--tttatagc
cc-tttgtcatgtgt-ggcggttgggactgagg-gatgcagcgtg-c---cg-cg-a--g
g-c-tgg-----------------g---t--tt-------cgaccang-ttcacgcttag
gatgttggc-ttttaatggcttcaatcgacccgt
>AF024444_Amanita_ceciliae
tcccctagtaagt-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-ctt
ttttttcttctatggctgtccgagttgtaatctagagaagcgcttacctgcgctggacca
tgtataa-gtctcctggaatggagcgtcgcagagggtgagaatcccgtctttgacatgga
c-tg-cc-agcgtg-ttgtggt-gcgctctcaaagagtcgagttgtttgggaatgcagct
ctaaacgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-gagggatcagcct--agc----
--tttt----tgcc-ggg-tgaatttcctggtc-tgacaggccaacatcgg-tctcgact
gctggaaaagagcg-gggggaatgtggcacc---tt--c----gggtgtg--tttatagc
cc-tttgttatatgc-ggcggtcgggaccgagg-gatgcagcgtg-c---cg-tgaa--g
g-c-tgg-----------------g---t--tt-------cgaccacg-ttcacgcttag
gatgttggc-ttttaatggcttcaatcgacccgt
>AY436493_Amanita_liquii
tcccctagtaact-gcgagtgaa-cgggaaaagctcaaatttgaaatct-ggcagt-ctt
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcgctggacca
tgtataa-gtctcctggaatggagcgtcgcagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-cggc-tggggatcaacct--agctg--
--tctt----tgct-ggg-tgaatttcctagtc-tggcaggccaacatcag-tcttgact
gctggaaaagagcg-gggggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-tttgtcatatgt-ggcagtcgggactgagg-gatgcagcgtg-c---cg-tg-a--g
g-c-cgg-----------------g---t--tt-------cgaccatg-ttcacgcttag
gatgttggc-ttttaatggcttcaatcgacccgt
>AF024455_Amanita_fulva
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-cta
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcaacct--agctgt-
--cttt----tgct-ggg-tgaatttcctagtc-tgacaggccaacatcag-tcttgact
gctggaaaagagca-gagggaatgtggcacc---tt--c----gggtgtg---ttatagc
cc-tttgtcatatgt-ggcggttgggactgagg-gatgcagcgtg-c---cg-cg-a--g
g-c-tgg-----------------g---t--tt-------cgaccacg-ttcacgcttag
gatgttggc-ttttaatggcttcaatcgacccgt
>AY436496_Amanita_orientifulva
tcccctagt-act-gcgagtgaagcgggaaaagctcaaatttgaaatctgggcagt-cta
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcgtcgcagagggtgagaatcccgtctttgacatgga
c-cg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-cggc-tagggatcaacct--agc--t-
--cttt----tgct-ggg-tgaatttcctattc-tgacaggccaacatcag-tttcgact
gctggaaaagagcg-gagggaatgtggcacc---tt--c----gggtgtg---ttatagc
cc-tttgtcatatgt-ggca-ccgggactgagg-gatgcagcgtg-c---cg-cg-a--g
g-c-tgg-----------------------------------------------------
----------------------------------
>AF097373_Amanita_fulva
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-cta
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-cggc-tagggatcaacct--agc--t-
--cttt----tgct-gggttgaatttcctattc-tgacaggccaacatcag-ttttgact
gctggaaaagagca-gagggaatgtggcacc---tt--c----gggtgtg---ttatagc
cc-tttgtcatatgt-ggcagtcaggactgagg-gatgcagcgtg-c---cg-cg-a--g
g-c-tgg-----------------g---n--tt-------tgaccacg-ttcacgcttag
gatgttggc-ttttaatggctccaatcgacccgt
>AF097374_Amanita_vaginata
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------tttggaaagaga-ttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcaacct--atcta--
--tttt----tgct-ggg-tgaa-ttcctagtt-tgacaggccaacatcat-tcttgact
gctggaaaagagca-gaaggaatgtggcacc---tt--t----gggtgtg---ttatag-
cc-tttgtcatatgt-ggcagttgggactgagg-gatgcagcgtg-c---cg-cg-a--a
g-c-tgg-----------------g---t--tt-------cgaccacg-ttcacgcttag
gatgttggc-ttttaatggcttcaatcgacccgt
>AF024466_Amanita_nivalis
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-ctt
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcaacct--agcta--
--tttt----tgct-ggg-tgaattttctagtc-tgacaggccaacatcag-tcttgact
gctggaaaagagca-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-tttgtcatatgt-agcagttgggactgagg-gatgcagcgtg-c---cg-cg-a--g
g-c-tgg-----------------g---t--tt-------cgaccacg-ttcacgcttag
gatgttggc-ttttaatggcttcaatcgac----
>FJ890045_Amanita_humboldtii
----ctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-ctt
ttttttcttctttggctgtccgagttgtaatctaaagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcgtcccagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcaacct--agctat-
--tttt----tgct-ggg-tgaatttcctagtc-tgacaggccaacatcag-tcttgacc
gctggaaaagagca-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-tttgtcatatgc-agcagttgggactgagg-gatgcagcgtg-c---cg-cg-a--g
g-c-tgg-----------------g---t--tt-------cgaccacg-ttcacgcttag
gatgttggc-ttttaatggcttcaatcgacccgt
>AF024440_Amanita_angustilamellata
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-ctt
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcgtcgcagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcaacct--agctat-
--tttt----tgct-ggg-tgaatttcctagtc-tgacaggccaacatcag-tcttgact
gctggaaaagagca-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-tctgtcatatgt-agcagttgggactgagg-gatgcagcgtg-c---cg-cg-a--g
g-c-tgg-----------------g---t--tt-------cgaccacg-ttcacgcttag
gatgttggc-ttttaatggcttcaatcgacccgt
>FJ705276_Amanita_submembranacea
----------act-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-ctt
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcctcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgcg-ttgtggt-gcgctctcaaagagtcgagttgtttgggaatgcagct
ctaaacgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-cggc-tggggatcaacct--agccatt
tttttt----ggct-ggg-tgaatttcctagtc-tgacaggccaacatcag-tcttgact
gccggaaaagagtg-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-tccgtcatatgc-ggcagtcgggactgagg-gatgcagtgtg-c---cg-cg-a--g
g-c-tgg-----------------g---t--tt-------tgaccacg-ttcacacttag
gatgttggc-ttttaatggctccaatcgacccgt
>AY228351_Amanita_constricta
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-ctt
ttttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcactggacca
tgtataa-gtctcctggaatggagcctcacagagggtgagaatcccgtctttgacatgga
c-cg-cc-agtgcg-ttgtggt-gcgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-ctgc-tagggatcaacct--agctatt
--cttt----ggct-ggg-tgaatttcctggtc-tgacaggccaacatcag-tcttgact
gccggaaaagagcg-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-tctgtcatatgc-ggcggtcgggactgagg-gatgcagcgtg-c---cg-cg-a--g
g-c-tgg-----------------g---t--tt-------cgaccacg-ttcacgcttag
gatgt-----------------------------
>FN557542_Uncultured_ectomycorrhizal
ncccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcagt-cct
ttttttcttctttggctgtctgagttgtaatctagagaagtgcttacctgcgctggacca
tgtacaa-gtctcctggaatggagcatcgcagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcagccc--agctgt-
--tttt----tgct-ggg-tgaatttcctagta-tgacaggccaacatcag-ttctgact
gctggaaaagagca-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
ct-tttgtcatatgt-ggcagttgggactgagg-gatgcagcgtg-c---cg-ca-a--g
g-c-cag-----------------gtttt--tt-------tgaccatg-ttcatgcttag
gatgttggc-ttttaatggcttcaatcgacccgt
>FJ236806_Amanita_coacta
---------------------------------------------------gcagt-ctc
ctttttcttctttggctgtccgagttgtaatctagagaagtgcttacctgcgctggacca
tgtataa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tc-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtta-tgt-tggc-tagggatcaaccc--agccact
--tttt----tgct-ggg-tgaatttcctagtcttgacaggccaacatcag-ttctgact
gccagaaaagagca-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
ct-tttgccatatgt-gacagccgggactgagg-gatgcagcgcgcc---cg-ca-a--g
g-g-cgg-----------------g---t--tt-------cgaccacg-tccgcgcttag
gatgttggctttttaatgggttcaatcgacccgt
>GQ925378_Amanita_sp
tcccttagtaact-gcgagtgaagtgggaaaagctcaaatttgaaatct-----------
-------catcttggctgtctgagttgtaatttagagaagtg-ctacctgtactggaccg
tgtataa-gtctcctgggatggagcgtcatagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgcg-ttgtggt-gtactttcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagtactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacacttgatgtcagttg-tgt-tggc-taggattcaaccc--ggct---
--tttt----tgct-agg-tgaatttccttgtc-tgacaggccaacatcag-ttttgact
gttagaaaaaggca-aggggaatgtggcacc---tt--t----gggtgtg---ttatagc
ct-tttgtcatatgt-gacagtcgggactgagg-tatgcagcgtg-c---cg-ca-a--g
g-c-tgg-----------------g---t--tt-------cgaccacg-ttcgcccttag
gatgttggc---ttaatggcattaattgacccgt
>GQ250426_Amanita_sp
tcccttagtaact-gcgagtgaagtgggaaaagctcaaatttaaaatct-ggcagt-ctg
aatttacttctttggctgtccgagttgtaatctagagaagtg-ctacctgtactggacca
tgtacaa-gtctcctgggatggagcatcacagagggtgagaatcccgtctatgacatgga
c-ta-cc-agtgtg-ttgtgga-gtactttcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaaggactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacacttgatgtcagttg-tgt-tagc-tggggatcagcct--agca---
--tttt----tgct-tgg-tgaatttcctggtg-tgacaggccaacatcag-tttcgayt
gctggagaaaggca-gacggaatgtggcacc---tt--t----gggtgtg---ttatagc
tt-tctgtcagatgt-agcagtcgggactgagg-tatgcagtgcg-c---cg-ta-a--g
g-c-agg-----------------g---t--tt-------cgaccaca-ctcgcacttag
gatgttggt---ttaatggcatcaattgacccgt
>AF024458_Amanita_hemibapha_var_ochracea
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcagt-g--
----------gttcactgcccgagttgtaatctagagaagtg-ttgctcacactggacca
tgtataa-gtcttctggaatgaagcgtcatagagggtgagaatcccgtctttgacatgga
c-tc-cc-agtgtatttgtagc-atgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaacctccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaaaagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtca-cat-tggc-cagggatcaactt--g------
---ctt---------aag-tgtacttcctgg-c-tgatgggccaacatcag-ctttgact
gtcagagaagggta-gggggaatgtggcaccc--ttctt----gggtgtg---ttatagc
cc-tctgtcatatat-ggccgttggggctgagg-aatgcagcgcg-c---ca-ca-a--g
g-c-cgg-----------------g---c--tt-------cgaccacg-ttcgcgcttag
gatgttggc---ataatggctttaatcgacccgt
>AF024443_Amanita_caesarea
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcagt-g--
----------gctcactgcccgagttgtaatctagagaagtg-ttgctcacactggacca
tgtataa-gtcttctggaatgaagcgtcatagagggtgagaatcccgtctttgacatgga
c-tc-cc-agtgtatttgtagt-atgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaacctccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaaaagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtca-cat-tggc-cagggatcaactt--g------
---ctt---------aag-tgtacttcctgg-t-tgatgggccaacatcag-ctttgact
gtcagagaagggta-gggggaatgtggcaccc---tctt----gggtgtg---ttatagc
cc-tctgtcatatat-ggccgttggggctgagg-aatgcagcgcg-c---cg-ca-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcgcgcttag
gatgttggc---ataatggctttaatcgacccgt
>GQ250416_Amanita_aff_lanei
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcagt-g--
----------gttcactgcccgagttgtaatctagagaagtg-ttgctcacactggacca
tgtataa-gtcttctggaatgaagcgtcatagagggtgagaatcccgtctttgacatgga
c-tc-cc-agtgtatttgtagc-atgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaacctccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaaaagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtca-cat-tggc-cagggatcaaccc--aagc---
--tttt---------gag-tgtacttcctgg-c-tgatgggccaacatcag-ctttgact
gtcagagaagggta-gggggaatgtggcaccc--ttctt----gggtgtg---ttatagc
cc-tctgtcatatat-ggccgttggggctgagg-aatgcagcgcg-c---ca-ca-a--g
g-c-cgg-----------------g---c--tt-------cgaccacg-ttcgcgcttag
gatgttggc---ataatggctttaatcgacccgt
>AF024488_Amanita_yuaniana
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcagt-c--
----------tttggctgtccgagttgtaatctagagaagtg-ttgcccacactggaccg
tgtataa-gtcttctggaatgaagcgtcatagagggtgagaatcccgtctttgacatgga
c-tc-cc-agtgta-ttgtggc-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaacctccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtca-cat-tggc-cagggatcaagcc--agct---
--cttt----tgtt-ggg-tgtatttcctggtt-tgatgggccaatgtcag-ttttgact
gctagagaaggaca-gagggaatgtggcacc---ttccg----gggtgtgtttttatagc
ct-tttgtcatatat-agcagttgggactgagg-aatgcagcgcgcc---ta-ca-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcgcgctttg
gatgttggc--aataatggctttaatcgacccgt
>GQ925369_Amanita_sp
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcagt-c--
----------tttggctgtccgagttgtaatctagagaagtg-ttgcccacactggaccg
tgtacaa-gtcttctggaatgaagcgtcatagagggtgagaatcccgtctttgacatgga
c-tc-cc-tgtgta-ttgtggc-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaacctccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagttg-cat-tggc-cagggatcaacct--agct---
--cttt----tgct-ggg-tgtacttcctgg-c-cgatgggccaatgtcag-tttcgact
gctagacaagggca-gagggaatgtggcacc---tcc------gggtgtg---ttatagc
ct-tgtgtcatatat-ggcagttgggactgagg-aatgcagcgcgcc---ca-cacg--g
g-c-cgg-----------------g---t--tt-------cgaccatgtttcgcgctttg
gatgttggc---ataatggctttaatcgacccgt
>AF024462_Amanita_longistriata
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-gacagt-c--
----------tttggctgtccgagttgtaatctagagaagtg-ttgcccacactggaccg
tgtacaa-gtcttctggaatgaagcgtcatagagggtgagaatcccgtctttgacatgga
c-tc-cc-agtgta-ttgtggc-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaacctccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtca-cat-tggc-cagggatcagcct--agct---
--cttt----tgct-gag-tgtacttcctggtt-tgatgggccaatgtcag-ttttgact
gccagagaagggca-gagggaatgtggcacc---ttccg----gggtgtg---ttatagc
ct-tttgttatatat-ggcagttgggactgagg-aatgcagcgcgcc---cg-caag--g
g-c-cgg-----------------g---t--tt-------cgaccacr-ttcgcgctttg
gatgttggc------------------------a
>AF024459_Amanita_incarnatifolia
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcagt-c--
----------tttggctgtccgaattgtaatctagagaagtg-ttgcccacactggaccg
tgtataa-gtcttctggaatgaagcgtcatagagggtgagaatcccgtctttgacatgga
c-tc-cc-agtgta-ttgtggc-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaacctccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtca-cat-tggc-cagggatcagccc--agct---
--cttt----tgct-aag-tgcacttcctggtt-tgatgggccaatatcagtttttgact
gccagagaagggca-gaaggaatgtggcacc---ttccg----gggtgtg---ttatagc
ct-tttgtcatatat-ggcagttgggactgagg-aatgcagcgcgcc---ca-caag--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcgcgctttg
gatgttggc--rataatggctttaatcgacccgt
>AF024445_Amanita_chepangiana
tcccctagtaact-gcgagtgaagtgggaaaagctcaaatttaaaatct-ggcagt-c--
----------tttggctgtccgagttgtaatctagagaagtg-tgtcctacactggactg
tgtataa-gtcttctggaatgaagcgtcatagagggtgagaatcccgtctttgacacaga
c-tc-cc-agtgta-ttatggc-atgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaacctccatctaaagctaaatattggcaagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagttg-cat-tggc-cggggatcagcct--agct---
--cttt----tgct-tgg-tgtacttcctgg-t-cgatgggccaacatgag-ttttgact
gccagagaagggca-gagggaatgtggcacc---tcc------gggtgtg---ttaaagc
ct-tctgtcatatat-gtcagttgggactgagg-aatgcagcatg-c---cg-ca-a--g
g-c-cag-----------------gtcat--ct-------agaccatg-ttcatgctttg
gatgttggc---ataatggctttaatcgacccgt
>GQ925376_Amanita_sp
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcag-----
----------ccttgctgtccgagttgtaatctaaagaagtg-ttgcctgcgctggaccg
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacacgga
c-tg-cc-agtgtg-atgtggc-gcgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtga-cat-tgac-tggggatcagcct--gcct---
--cttt----tggt-ggg-tgcagttcctgg-c-tgatgggccaacatcag-ttttgagt
gctggagaagggtg-ttgggaatgtggcacc---tt--c----gggtgtg---ttatagc
cc-agtgtcggatgc-agcatttgagactgagg-aatgcagcacg-c---cg-ta-a--a
ggc-ctg-----------------gt-----tt-------cgaccaag-atcgtgctttg
gatgttggt---gtaatggctttaatcgacccgt
>GQ925372_Amanita_sp
tcccctagtaact-gcgagtgaagcgggaagagctcaaatttgaaatct-ggcggt-gat
----------tttagccgtccgagttgtaatctagagaagtg-ttgcctgcgctggaccg
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacacgga
c-ta-cc-agtgcg-ttgtggc-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacgcttgaagtcagtcg-cgt-tgac-cggggatcagcct--gcct---
--gttt----cggt-agg-tgaacttcctgg-c-tgacgggccaacatcag-ttttgagt
ggcggacaagggtg-ttgggaatgtggcacc---tt--c----gggtgtg---ttatagc
cc-tgcatcggatgc-ggcacttgggactgagg-aatgcagcacg-c---cg-ca-a--g
g-c-ctg-----------------gtcat-----------tgaccaagacccgtgcttgg
gatgttggc--aataatggctttaatcgacccgt
>AF097369_Amanita_roseo-tincta
tcccctagtaact-gcgagtgaagagggaagagctcaaatttagaatct-ggcagt-a--
----------ttttgctgtccgagttgtaatctagagaagtg-ctgcccgtgctggacca
tgtacaa-gtctcctggaatggagcgtcatagagggtgagaatcccgtctttgacatgga
c-tc-cc-agtgcatttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggccagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtca-tgtgtcag-ccaggatcaacct--actat--
--tgct----tgct-ggg-tgtacttcctgatc-tgatgggccaacatcag-tttcgact
gcnggagaagggta-gagggaatgtggcacctt-tt--t----tggtgtg---ttatagc
tc-tctgtcagatgc-agtggtcaggactgagg-aaggcagcatg-cccaca-aa-g--g
g-c-cgg-----------------gt-----tt-------cgaccacg-ttcatgctgag
gatgttggc---ataatggctttaatcgacccgt
>AY436497_Amanita_orientigemmata
tcccttagt-act-gcgagtgaagagggaagagctcaaatttaaaatct-ggcagt-t--
----------ttttgctgtccgagttgtaatctagagaagtg-ctgcccgtgctggacca
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtacatttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtcg-tgt-cggc-cagggatcaaccc--agtttt-
--attc----tgct-ggg-tgtatttcctgatc-tgatgggccaacatcag-ttttgact
gctggagaaggata-gggggaatgtggcacc---tt--tg---gggtgtg---ttatagc
tc-tctgttatatgc-agtggttgggactgagg-aaagcagcatg-c---cg-ca-a--g
g-c-cag-----------------gt-----tt-------cgaccatg-ttcatgctgag
gatgttggc---ataatggctttaatcgacccgt
>AF024480_Amanita_sychnopyramis
tcccctagtaact-gcgagtgaagagggaagagctcaaatttaaaatct-ggcagt-g--
----------tttcactgtccgagttgtaatctagagaagtg-ctgcccgtgctggacca
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgcatttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtca-tgt-cggc-cagggatcaaccc--agtc---
--attt----tgct-ggg-tgtacttcctgatc-tgatgggccaacatcag-ttttgact
gctggaaaagggca-gagggaatgtggcact---tt--c----gggtgtg---ttatagc
tc-tctgtcagatac-agtggttgggactgagg-aaagcagcatg-c---cg-ca-a--g
g-c-cag-----------------gt-----tt-------taaccatg-ttcatgctgag
gatgttgg--------------------------
>AF024474_Amanita_sinensis
tcccctagtaact-gcgagtgaagagggaagagctcaaatttaaaatct-ggcagt-g--
----------ttttgctgtctgagttgtaatctagagaagtg-ctgcccgtgctggacca
tgtacaa-gtctcctggaatggagcatcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgcatttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacacttaaagtcagtca-tgt-cggc-cagggatcaaccc--agtttt-
--tctt----tgct-ggg-tgtacttcctgatc-tgacaggccaacatcag-ttttgact
gctggagaaggata-gagggaatgtggcacc---tc--t----gggtgtg---ttatagc
tc-tctgtcagatgc-agtggtggggactgagg-aaggcagcatg-c---ca-ca-a--g
g-c-cag-----------------gt-----tt-------agaccatg-ttcatgctgag
gatgttggc---ataatggctttaattgacccgt
>AF024477_Amanita_subfrostiana
tcccttagtaact-gcgagtgaagagggaagagctcaaatttaaaatct-ggcagt-g--
----------ctttgctgtccgagttgtaatctagagaagtg-ctacccgtgctggacca
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgcatttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtcg-tgt-cggc-cagggatcaactc--agttt--
--tttc----tgct-ggg-tgtacttcctgatc-tgatgggccaacatcag-ttttgact
gctggagaaggata-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-tctgtcagatgc-agtggttgggactgagg-aaagcagcatg-c---cg-aa-a--g
g-c-cgg-----------------gtcag--tt-------tgaccacg-ttcatgctgag
gatgttggc---ataatggctttaatcgacccgt
>AF024453_Amanita_frostiana
tcccttagtaact-gcgagtgaagagggaagagctcaaatttaaaatct-ggcagt-g--
----------ctttgctgtccgagttgtaatctagagaagtg-ctgcccgtgctggacca
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtcttcgacatgga
c-tg-cc-agtgcatttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtcg-tgt-cggc-cagggatcaactc--agttt--
--tatt----tgct-ggg-tgtacttcctgatc-tgatgggccaacatcag-ttttgact
gctggagaaggata-gagggaatgtggcacc-t-tt--t----tggtgtg---ttatagc
tc-tctgtcagatgc-agtggttgggactgagg-aaagcagcatg-c---cg-ca-a--g
g-c-cgg-----------------gtca---tt-------tgaccacg-ttcatgctgag
gatgttggc---ataatggctttaatcgacccgt
>EU071974_Amanita_muscaria
tcccttagtaact-gcgagtgaagagggaagagctcaaatttaaaatct-ggcagt-g--
----------tcttgctgtccgagttgtaatctagagaagtg-ctgcccgtgctggacca
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgcatttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtcg-tgt-cggc-cagggatcaactc--agctt--
--tctt----tgct-ggg-tgtacttcctgatc-tgatgggccaacatcag-ttttgact
gctggagaaggata-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-tctgtcagatgc-agtggttgggactgagg-attgcagcatg-c---cg-ca-a--g
g-c-cgg-----------------gtcgt--tt-------cgaccacg-ttcatgctgag
gatgttggc---ataatggctttaatcgacccgt
>GQ250421_Amanita_aff_pantherina
tcccttagtaact-gcgagtgaagagggaagagctcaaatttaaaatct-ggcagt-g--
----------ttttgctgtccgagttgtaatctagagaagtg-ctgcccgtgctggaccg
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgcatttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtcg-tgt-cggc-cagggatcaactc--agttt--
--tctt----tgct-ggg-tgtacttcctgatc-tgatgggccaacatcag-ttttgact
gctggagaaggata-gagggaatgtggcacc---tt--c----gggtgtg---ttatagc
tc-tctgtcggatgc-agtggttgggactgagg-aaagcagcatg-c---cg-ca-a--g
g-c-cgg-----------------gt-----tt-------cgaccacg-ttcatgctgag
gatgttggc---ataatggctttaatcgacccgt
>AF024468_Amanita_pantherina_var_lutea
tcccctagtaact-gcgagtgaagagggaagagctcaaatttaaaatct-ggcagt-g--
----------ctttgctgtccgagttgtaatctagagaagtg-ctgcccgtgctggaccg
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgcatttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtcg-tgt-cggc-cagggatcaactc--agttt--
--tttc----tgct-ggg-tgtatttcctgatc-tgatgggccaacatcag-ttttgact
gctggagaaggata-gagggaatgtggcacc---tc--c----gggtgtg---ttatagc
tc-tctgtcggatgc-agtggttgggactgagg-aaagcagcacg-c---cg-ca-a--g
g-c-cgg-----------------gtcgt--tt-------cgaccatg-ttcgtgctgag
gatgttggc---ataatggctttaatcgacccgt
>GQ250414_Amanita_gemmata
--------------------------------------------------ggcagt-g--
----------ttttgctgtccgagttgtaatctagagaagtg-ctgcccgtgctggaccg
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgcatttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtcg-tgt-cggc-cagggatcaactc--agttt--
--tttc----tgct-ggg-tgtacttcctgatc-tgatgggccaacatcag-ttttgact
gctggagaaggata-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-tctgtcggatgc-agtggttgggactgagg-aaagcagcatg-c---cg-ca-a--g
g-c-cgg-----------------gttgt--tt-------caactacg-ttcatgctgag
gatgttggc---ataat-----------------
>AF024473_Amanita_rubrovolvata
tcccctagtaact-gcgagtgaagagggaagagctcaaatttaaaatct-ggcagt-c--
----------ttttgctgtccgagttgtaatctagagaagtg-ctgcccgtgctggacca
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgca-ttgtggt-atgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtcg-tgt-cggc-cagggatcaactc--agttg--
--tttc----tgct-ggg-tgtacttcctgatc-tgatgggccaacatcag-ttttgact
gctggagaaggata-gagggaatgtggcacc---tc--t----gggtgtg---ttatagc
tc-tctgtcggatgc-agtggtcaggactgagg-aaagcagcatg-c---cg-ca-a--g
g-c-tgg-----------------gt-----tt-------taaccacg-ttcatgctgag
gatgttggc---ataatggctttaatcgacccgt
>AY436487_Amanita_altipes
tcccctagtaact-gcgagtgaagagggaagagctcaaatttaaaatct-ggcagt-a--
----------ttttgctgtccgagttgtaatctagagaagtg-ctgcccgtgctggacca
tgtacaa-gtctcctggaatggagcgtcatagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgcatttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtcg-tgt-cggc-cagggatcaactc--agttt--
--tttc----tgct-ggg-tgtacttcctgatc-tgatgggccaacatcag-ttttgact
gctggagaaggata-gagggaatgtggcacc---tc--c----gggtgtg---ttatagc
tc-tctgtcagatgcaagtggttgggactgagg-aaagcagcatg-c---cg-ca-a--g
g-c-cgg-----------------gtt----tc-------aacccacg-ttcatgctgag
gatgttggc---ataatggctttaatcgacccgt
>AF097371_Amanita_gemmata
tcccctagtaact-gcgagtgaagagggaagagctcaaatttgaaatct-ggcagt-g--
----------ttttgctgtccgagttgtaatctagagaagtg-ctgcccgtgctggacca
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgcatttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtcg-tgt-cggc-cagggatcaactc--agtat--
--tatc----tgct-ggg-tgtacttcctgatc-tgatgggccaacatcag-ttttgact
gctggagaaggata-gagggaatgtggcacc---tt--c----gggtgtg---ttatagc
tc-tctgtcggatgc-agtggttgggactgagg-aaagcagcatg-c---cg-ca-a--g
g-c-cgg-----------------gtcgt--tt-------cgaccacg-ttcatgctgag
gatgttggc---ataatggctttaatcgacccgt
>AF097370_Amanita_farinosa
tcccttagtaact-gcgagtgaagagggaagagctcaaatttgaaatct-ggcagt-g--
----------ttttactgctcgagttgtaatctagagaagtg-ttacccgtgctggacca
tgtacaa-gtctcctggaatggagcatcatagagggtgagaatcctgtctttgacatgga
c-ta-cc-agtgcaattgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcaagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacacttaaagtcagtga-tgt-cggc-cagggatcaagtc--cgcat--
--tttttaaatgct-ggg-tgtacttcctgatc-tgacaggtcaacatgag-ttttgact
gctggaaaaggatt-gggggaatgtggcacc---tt--c----gggtgtg---ttatagc
tc-tctatcaaatgc-agtggttgggactgagg-aaggcagcacg-c---ca-ca-a--g
g-c-cga-----------------gt-----tt-------cgactacg-ttcgtgctgag
gatgttggc---ataatggctttaattgacccgt
>FJ890035_Amanita_xylinivolva
tcccctagtaact-gcgagtgaagagggaagagctcaaatttaaaatct-gacagt-g--
----------ttttgctgtccgagttgtaatctagagaagtg-ttacccgtgctggacca
tgtacaa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtca-tgt-cggc-cagggatcaactt--agctt--
--tctt----tgct-ggg-tgtacttcctgatc-tgatgggccaacatcag-ttttgact
gctggagaaggata-gagggaatgtggcacc---tc--c----gggtgtg---ttatagc
tc-tttgtcggatgc-agtggttgggactgagg-aaagcagcatg-c---cg-ta-a--g
gcc-cgg-----------------gt-----tt-------cgaccacg-ttcatgctgag
gatgttggc---ataatggctttaatcgacccgt
>AF024464_Amanita_mira
tcccttagtaact-gcgagtgaagagggaagagctcaaatttgaaatct-gacagt-g--
----------ttttgctgttcgagttgtaatctagagaagtg-ctgcccgtgctggacca
tgtacaa-gtctcctggaatggagcgtcatagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgca-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatwgcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttaaagtcagtcg-tgt-cggc-cagggatcaacct--agttta-
--tctt----tgct-ggg-tgtacttcctgatc-tgatgggccaacatcag-ttttgact
gctggaaaagggca-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-tctgtcatatgc-agtggttgggactgagg-aaagcagcatg-c---ca-tata--g
g-c-cgg-----------------gt-----tt-------cgaccacg-ttcatgctgag
gatgttggc---ataatggctttaatcgacccgt
>AY436489_Amanita_aff_citrina
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------ttttgctgtccgagttgtaacctagagaagtg-taacctgggctggacca
tgtacaa-gtctcctggaatggggcatcgcagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtca-tgt-tggt-tggggatcagcct--ggca---
--gatt-----gtt-ggg-tgtacttcctgg-t-tgacaggccaacatcag-ttttgact
gccagagaaaggcc-aagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-ttggtcgtatgt-ggcggttgggactgagg-aaagcagtgcg-c---cg-aa-a--g
g-c-agg-----------------g---t--tt-------cgaccaca-ttcgcactgag
ga--------------------------------
>AF024446_Amanita_citrina
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------ttttgctgtccgagttgtaacctagagaagtg-taacctgggctggacca
tgtacaa-gtctcctggaatggagcatcgcagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtca-tgt-tggt-tggggatcagcct--ggca---
--gatt-----gcc-ggg-tgtacttcctgg-t-tgacgggccaacatcag-ttttgact
gccagagaaaggcc-aagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-ttggycgtatgt-ggtggttgggactgagg-agagcagtgcg-c---cg-aa-a--g
g-c-agg-----------------g---t--tt-------cgaccaca-ttcgcactgag
gatgttggc---ataatggctttaagcgacccgt
>FJ890046_Amanita_citrina
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-gacagt-g--
----------ttttgctgtccgagttgtaacctagagaagtg-taacctgtgctggacca
tgtacaa-gtctcctggaatggggcatcgcagagggtgagaatcccgtgtttgacatgga
c-ta-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtca-tgt-tggg-tggggatcagcct--ggca---
--gatt-----gtt-ggg-tgtacttcctgg-t-tgacgggccaacatcag-ttttgact
gccagagaaaggtg-aagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-tttgtcgtatgt-ggtggttgggactgagg-aaagcagtgcg-c---cg-aa-a--g
g-c-ggg-----------------g---t--tt-------cgaccaca-ttcgcactgag
gatgttggc---ataatggctttaagcgacccgt
>AY436500_Amanita_porphyria
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------ttttgctgtccgagttgtaacctagagaagtg-taacctgtgctggacca
tgtataa-atctcctggaatggagcatcgcagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtca-tgt-tgac-tggggatcagcct--ggca---
--gttt-----gtt-ggg-tgtacttcctgg-t-tgacgggccaacatcag-ttttgact
gccagagaaaggcc-aagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-ttggtcgtatgt-ggtggctgggactgagg-aaagcagtgcgcc---cg-aa-a--g
g-c-agg-----------------g---t--tt-------cgaccacatttcgcactgag
gatgttggc---ataatggctttaagcgacccgt
>GQ250423_Amanita_silvicola
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcggt-g--
----------tttcactgtccgagttgtaacctagagaagtg-taacctgtactggaccg
tgtacaa-gtctcctggaatggagcatcacagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagttg-cat-tggc-tggggatcaacct--taca---
--tttc----tgtt-ggg-tgtacttcctgg-t-tgatgggccaacatcag-ttttgact
gccagaaaaaggcc-aagtgaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-ttggttgtatat-ggtggttgggactgagg-aatgcagtgtg-c---cg-aa-a--g
g-c-cgg-----------------g---t--tt-------tgaccacg-ttcacactgag
gatgttggc---ataatggctttaagcgacccgt
>AY436501_Amanita_sepiacea
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------tttcactgtccgagttgtaacctagagaagtg-taacctgcactggaccg
tgtacaa-gtctcctggaatggagcatcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacatttgaagtcagtcg-cgt-tggc-tggggatcaacct--gact---
--tttt----ggtt-aag-tgtacttcctgg-g-tgacgggtcaacatcag-ttttgact
gccagaaaaaggct-aag-gaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-ttggtcgtatgt-ggtggttgggactgagg-aaagcagtgtg-c---cg-aa-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacactgag
gatgttggc---ataatggctttaagtgacccgt
>AF024470_Amanita_pilosella
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagc-a--
----------ttttgttgtccgagttgtaacctagagaagtg-taacctgtgctggaccg
tgtataa-gtttcctggaatggagcatcacagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtcg-cgt-tagc-tggggatcagcct--gaca---
--tt-------gtt-ggg-tgcacttcctgg-t-tgacgggccaacatcag-ttttgact
gccagaaaaaggcc-aagggaatgtggcacc---tt--t----gggtgtg---ttatagc
ct-ttggtcatatat-ggtggttgggactgagg-aatgcagtgtg-c---cg-aa-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacactgag
gatgttggc---ataatggctttaagcgacccgt
>FJ890043_Amanita_rubescens
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------tttcactgtccgagttgtaacctagagaagtg-taacctgcgctggaccg
tgtataa-gtctcctggaatggagcatcacagagggtgagaatcccgtctttgacatgga
c-ca-cc-agcgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtcg-cgt-tggt-tggggatcagcct--gaca---
--tt-------gtt-ggg-tttacttcctgg-t-cgacgggccaacatcag-ttttgact
gccagaaaaaggcc-aaaggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-ttggtcgtatat-ggtggttgggactgagg-aaagcagcgtg-c---gg-aa-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacgctgag
gatgttggc---ataatggctttaagcgacccgt
>AF097381_Amanita_franchetii
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------tttcactgtccgagttgtaacctagagaagtg-taacctgcgctggaccg
tgtataa-gtctcctggaatggagcatcactgagggtgagaatcccgtctttgacacgga
c-ca-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtcg-cgt-cggt-tggggatcagcct--gaca---
--tt-------gtt-ggg-tgtacttcctgg-t-tgacgggccaacatcag-ttttgatt
gccagaaaaaggcc-aaaggaatgtggcacn---tt--t----gggtgtg---ttatagc
cc-ttggtcgtatat-ggtggttgggactgagg-aaagcagcgtg-c---cg-aa-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacgctgag
gatgttggc---ataatggctttaagcgacccgt
>FJ890041_Amanita_flavoconia
tcccttagtaactcgcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------tttcactgtccgagttgtaacctagagaagtg-taacctgcgctggaccg
tgtataa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacacgga
c-ta-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtcg-cgt-tggt-tggggatcagcct--gacat--
--tt-------gtt-ggg-tgtacttcctgg-t-tgacgggccaacatcag-ttttgact
gccagaaaaaggcc-aaaggaatgtggcacc---tt--t----gggtgtg---ttatagc
ct-ttggtcgtatat-ggtggttgggactgagg-aaagcagcgtg-c---cg-aa-a--g
g-c-cgg-----------------g---t--tt-------tgaccatg-ttcacgctgag
gatgttggc---ataatggctttaagcgacccgt
>EU522816_Amanita_flavoconia
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------tttcactgtccgagttgtaacctagagaagtg-taacctgcgctggaccg
tgtataa-gtctcctggaatggagcgtcacagagggtgagaatcccgtctttgacacgga
c-ta-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtcg-cgt-tggt-tggggatcagcct--gacat--
--tt-------gtt-ggg-tgtacttcctgg-t-tgacgggccaacatcag-ttttgact
gccagaaaaaggcc-agaggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-ttggtcgtatat-ggtggttgggactgagg-aaagcagcgtg-c---cg-aa-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacgctgag
gatgttggc---ataatggctttaagcgacccgt
>AF024452_Amanita_fritillaria
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------cttcactgtccgagttgtaacctagagaagtg-taacctgcgctggaccg
tgtataa-gtctcctggaatggagcatcacagagggtgagaatcccgtctttgacacgga
c-ta-cc-agtgca-ttgtggtttcgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtcg-cgt-tggt-tggggatcagcct--aaca---
--tt-------gtt-ggg-tgtacttcctgg-t-tgacgggccaacatcag-ttttgact
gccagaaaaaggcc-aaaggaatgtggcacc---ct--t----gggtgtg---ttatagc
cc-ttggtcgtatat-ggtggttgggactgagg-aaagcagcgtg-c---cg-aa-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacgctgag
gatgttggc---ataatggctttaagcgacccgt
>AF024451_Amanita_flavipes
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------tttcactgtccgagttgtaacctagagaagtg-taacctgtgctggaccg
tgtataa-gtctcctggaatggagcatcatagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ttgtggttgcgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtcg-cgt-tggt-tggggatcagcct--gaca---
--tt-------gtt-ggg-tgtacttcctgg-t-tgacgggccaacatcag-ttttgact
gccagaaaaaggcc-aaaggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-ttggtcgtatat-ggtggttgggactgagg-aaagcagcgtg-c---cg-aa-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacgctgag
gatgttggc---ataatggctttaagcgacccgt
>AF024449_Amanita_excelsa
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------tttcactgtccgagttgtaacctagagaagtg-taacctgtgctggaccg
tgtacaa-gtctcctggaatggagcatcacagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ttgcggttgcgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtcg-cgt-tggt-tggggatcagcct--gaca---
--tt-------gtt-ggg-tgtatttcctgg-t-cgacgggccaacatcag-ttttgact
gccagaaaaaggcc-aaaggaatgtggcacc---tt--t----gggtgtg---ttatagc
cc-ttggtcgtatat-ggtggttgggactgagg-aaagcagcgtg-c---cg-aa-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacgctgag
gatgttggc---ataatggctttaagcgacccgt
>AF097379_Amanita_brunnescens
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------tttcattgtccgagttgtaacctagagaagtg-taacctgtgctggaccg
tgtacaa-gtctcctggaatggagcatcacagagggtgagaatcccgtctttgacacgga
c-ta-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtcg-tgt-tggc-tggggatcaacct--gac----
--ttat----tgtt-agg-tgtatttcctgg-t-tgacgggccaacatcag-ttttgact
gccagaaaaaggcc-aagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tt-ttggtcgtatgt-ggtggttgggactgagg-acagcagtgcg-c---cgcaa-t--g
g-c-agg-----------------g---t--tt-------cgaccaca-ttcgcactgag
gatgttggc---ataatggctttaagcgacccgt
>AF097378_Amanita_citrina
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------tttcgctgtccgagttgtaacctagagaagtg-taacctgtgctggaccg
tgtacaa-gtctcctggaatggagcatcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtca-tgt-tggc-tggggatcagcct--gaca---
--ttta----tgtt-ggg-tgtacttcctgg-t-tgacgggccaacatcag-ttttgact
gccagaaaaaggcc-aagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-ttggtcgtatgt-ggtggttgggactgagg-aaagcagtgcg-c---cg-aa-a--g
g-c-agg-----------------g---t--tt-------cgaccaca-ttcgcactgag
gatgttggc---ataatggctttaagcgacccgt
>AF024447_Amanita_citrina_var_grisea
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcagt-g--
----------ttttgctgtccgagttgtaacctagagaagtg-taacctgcgctggacca
tgtacaa-gtctcctggaatggagcatcacagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtca-tgt-tagc-tggggatcagcct--gaca---
--tttt-----gtt-tgg-tgtacttcctgg-t-tgatgggccaacatcag-ttttgact
gccagaaaaagggc-aagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-ttggtcatatgt-ggtggttgggactgagg-aaagcagtgtg-c---ca-aa-a--g
g-c-agg-----------------g---tagtt-------ctaccaca-ttcacactgag
gatgttggc---ataatggctttaagcgacc---
>FJ890037_Amanita_sp
tcccttagtaact-gcgagtgaagagggataagctcaaatttaaaatct-ggcagt-g--
----------ttttgctgtccgagttgtaacctagagaagtg-taacctgtgctggacca
tgtacaa-gtctcctggaatggagcatcacagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ttgtggttgtgctctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtca-tgt-tggc-tggggatcagctt--gaca---
--tttt-----gtt-ggg-tgtacttcctgg-t-gaacgggccaacatcag-ttttgact
gccagagaaagtcc-aagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-ttggtcgtatgt-ggtggttgggactgagg-atagcagtgtg-c---cg-aa-a--g
g-c-agg-----------------g---t--tt-------cgaccaca-ttcgcactgag
gatgttggc---ataatggctttaagcgacccgt
>AY436495_Amanita_griseoverrucosa
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcagt-g--
----------ttctactgtccgagttgtaaactagagaagtg-cagcctgcgctggaccg
tgtacaa-gtcttctggaatgaagcatcacagagggtgataatcccgtctttgacatgga
c-ta-cc-agtgca-ttgtggttgtgcgctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatactggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtca-tgt-tggc-cggggatcagttt--ggct---
--aatt----tgctcgag-tgtatttcctgg-t-tgacgggtcaacatcag-ttttgact
gccagagaaaggccgaagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-ttggttgtatgt-ggcagtt-ggactgagg-aaagcagtgcg-c---cg-ca-a--g
g-c-agg-----------------g---t--tt-------cgaccacg-ttcgcactttg
gatgttggc-aaataatggctttaagcgacccgt
>AF024476_Amanita_strobiliformis
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttgaaatct-ggcggt-gt-
----------ttttactgtccgagttgtaagctagagaagtg-cagcctgcgctgaaccg
tgtataa-gtcttctggaatggggcatcatagagggtgagaaacccgtctttgacacgga
g-ta-cc-agtgca-ttgtggttgtgcgctcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaaaagtatgtgaaattg
ttgaaagggaaacatttgaagtcagaga-tat-tgac-tggggatcaactt--ggga---
--aaat----agct-gag-tgtgattcctgg-t-taatgggccaacatcagtttttgact
gctagagaaaggcc-aagggaatgtggcacc---ta--t----gggtgtg---ttatagc
tc-ttggttgtatgt-agtggttaggactgagg-aaagcagcgtg-c---ct-ta-t--g
g-a-ggg-----------------g---t--tt-------cgaccaca-ttcacgcttag
gatgttggc---a---------------------
>GQ250419_Amanita_ocreata
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcaga-tg-
----------tttgtctgtccgagttgtaacctagagaagtg-taacctgtgctggaccg
tgtacaa-gtctcctggaatggagcatcatagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ctgtggttgtgcactcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagctg-cat-tggc-tggggatcaagcc--agct---
--tatt----tgct-ggt-tgtacttcctgg-t-tgatgggccaacatcag-ttttgacc
atcagagaaaggcc-aagggaatgtggcacc---tttat----aggtgtg---ttatagc
cc-ttggttgtatgt-ggtggttgggactgagg-atagcagcgtg-c---ca-ca-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacgctttg
gatgttggc---ataatggctttaagcgaccc--
>FJ755189_Amanita_virosa
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcaga-tg-
----------cttgtctgtccgagttgtaacctagagaagtg-tagcctgtgctggaccg
tgtacaa-gtctcctggaatggagcatcatagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ctgtggttgcacactcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacacttgaagtcagctg-cat-tggc-tggggatcaagcc--agct---
--tatt----tgct-ggg-tgtacttcctgg-t-tgatgggccaacatcag-ttttgacc
atcagagaaaggca-aagggaatgtggcacc---tttat----aggtgtg---ttatagc
cc-ttggttgtatgt-ggtggttgggactgagg-atagcagcgtg-c---ca-ca-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacgctttg
gatgttggc---ataatggctttaagtgacccgt
>AF024486_Amanita_cf_virosa
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcaga-tg-
----------cttgtctgtccgagttgtaacctagagaagtg-taacctgtgctggaccg
tgtacaa-gtctcctggaatggagcatcatagagggtgagaatcctgtctttgacacgga
c-taccc-agtgca-ttgtggttgcgcactcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagctg-cat-tggc-tggggatcaagcc--agct---
--tatt----tgct-ggg-tgtacttcctgg-t-tgatgggccaacatcag-ttttgacc
atcagagaaaggca-gagggaatgtggcacc---tttat----aggtgtg---ttatagc
cc-ttggttgtatgt-ggtggttgggactgagg-atagcagcgtg-c---ca-ca-a--g
g-c-cgg-----------------g---t--tt-------cgactacg-ttcacgctttg
gatgttggc---ataatggctttaagcgacccgt
>AY325879_Amanita_arocheae
----------------------agcgggaaaagctcaaatttaaaatct-ggcaga-tg-
----------cttgtctgtccgagttgtaacctagaaaagtg-taacctgtgctggaccg
tgtacaa-gtctcctggaatggagcatcatagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ttgtggttgtgcactcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagctg-cat-tggc-tggggatcaagcc--agct---
--tatt----tgct-ggg-tgtacttcctgg-t-tgatgggccaacatcag-ttttgacc
atcagaaaaaggca-aagggaatgtggcatc---tttat----aggtgtg---ttatagc
cc-ttggttgtatgt-ggtggttgggactgagg-a-------------------------
------------------------------------------------------------
----------------------------------
>FJ890040_Amanita_sp
tcccctagtaactcgcgagtgaagcgggaaaagctcaaatttaaaatct-ggcaga-tg-
----------cttgtctgtccgagttgtaacctagagaagtg-taacctgtgctggaccg
tgtacaa-gtctcctggaatggagcatcatagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ctgtggttgcgcactcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagctg-cat-tggc-tggggatcaagcc--agct---
--tatt----tgct-ggg-tgtacttcctgg-t-tgatgggccaacatcag-ttttgacc
atcagagaaaggca-aagggaatgtggcatc---tttat----aggtgtg---ttatagc
cc-ttggttgtatgt-ggtggttgggactgagg-atagcagcgtg-c---ca-ca-a--g
g-c-tgg-----------------g---t--tt-------cgaccacg-ttcacgctttg
gatgttggc---ataatggctttaagcgacccgt
>AF097386_Amanita_virosa
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcaga-tg-
----------cttgtctgtccgagttgtaacctagagaagtg-taacctgtgctggacca
tgtacaa-gtctcctggaatggagcatcatagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ctgtggttgtgcactcgacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagctg-cat-tggc-tggggatcaagcc--agct---
--tatt----tgct-ggc-tgtacttcctgg-t-tgatgggccaacatcag-ttttgacc
atcagagaaaggca-aagggaatgtggcacc---tttat----aggtgtg---ttatagc
cc-ttggttgtatgt-ggtggttgggaatgagg-atagcagcgtg-c---aa-ca-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacgctttg
gatgttggc---ataatggctttaagcgacccgt
>DQ071721_Amanita_phalloides
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcaga-tg-
----------tttgtctgtccgagttgtaacctagagaagtg-taacctgtgctggaccg
tgtacaa-gtctcctggaatggagcatcatagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ctgtggttgcgcactcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacacttgaagtcagctg-cat-tggc-tggggatcaagcc--agct---
--tatt----tgct-ggg-tgtacttcctgg-t-tgatgggccaacatcag-ttttgacc
atcagagaaaggct-aagggaatgtggcacc---tttat----aggtgtg---ttatagc
cc-ttggttgtatgt-ggtggatgggactgagg-atagcagcgtg-c---cg-ca-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacgctttg
gatgttggc---ataatggctttaagtgacccgt
>GQ250420_Amanita_ocreata
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcaga-tg-
----------tttgtctgtccgagttgtaacctagagaagtg-taacctgtgctggaccg
tgtacaa-gtctcctggaatggagcatcatagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ctgtggttgcacactcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagctg-cat-tagc-tggggatcaagcc--agct---
--tttt----tgct-ggg-tgtacttcctgg-t-tgatgggccaacatcag-ttttgacc
atcagagaaaggct-aagggaatgtggcacc---tttat----aggtgtg---ttatagc
cc-ttggttgtatgt-gatggatgggactgagg-acagcagcgtg-c---cg-ca-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcacgctttg
gatgttggc---ataatggctttaagcgacccgt
>AY436492_Amanita_exitialis
tcccctagtaact-gcgagtgaagagggaagagctcaaatttaaaatct-ggcaga-tg-
----------tttgtctgtccgagttgtaacctagagaagtg-taacctgtgctggacca
tgtacaatgtctcctggaatggagcatcatagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgcg-ctgtggttgcacactcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaattcagctg-cat-tggc-tggggatcaagcc--agct---
--tatt----tgct-ggg-tgtatttcctgg-t-tgatgggccaacatcag-ttttgacc
atcagagaaaggct-aagggaatgtggcacc---tttat----aggtgtg---ttatagc
cc-ttggttgtatgt-ggtggttgggactgagg-acagcagcgtg-c---cg-ca-a--g
g-c-cag-----------------g---t--tt-------cgaccatg-ttcacgctttg
gatgttggc---ataatggctttaagcgacccgt
>AF097384_Amanita_bisporigera
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcaga-tt-
----------tttgtctgtccgagttgtaacctagagaagtg-taacctgtgctggaccg
tgtacaa-gtctcctggaatggagcatcatagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ctgtggttgcacactcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagctg-cat-tggc-tggggatcaagcc--agct---
--tatt----tgct-ggg-tgtacttcctgg-t-tgatgggccaacatcag-ttttgacc
atcagagaaaggct-aagggaatgtggcacc---tttat----aggtgtg---ttatagc
cc-ttggttgtatgt-gatggttgggactgagg-atagcagcgtg-c---cg-ca-a--g
g-c-cag-----------------g---t--tt-------cgaccatg-ttcacgctttg
gatgttggc---ataatggctttaagcgacccgt
>AF024479_Amanita_subjunquillea
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcaga-tt-
----------tttgtctgtccgagttgtaacctagagaagtg-taacctgtgctggaccg
tgtacaa-gtctcctggaatggagcatcatagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ctgtggttgcgcactcgacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagctg-cat-tggc-tggggatcaagcc--agct---
--tatt----tgct-ggg-tgtacttcctgg-t-tgatgggccaacatcag-ttttgacc
atcagagaaaggcc-aagggaatgtggcacc---tttat----aggtgtg---ttatagt
cc-ttggttgtatgt-ggtggttgggactgagg-atagcagcgtg-c---cg-ca-a--g
g-ctcgg-----------------g---t--tt-------cgaccacg-ttcacgcttgg
gatgttggc---ataatggctttaagcgacccgt
>AF024454_Amanita_fuliginea
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcaga-ct-
----------gttggctgtccgagttgtaacctagagaagtg-taacctgtgctggacca
tgtacaa-gtctcctggaatggagcatcatagagggtgagaatcccgtctttgacatgga
c-ta-cc-agtgca-ctaaggttgcgcactcaacgagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagctg-tgt-tggc-tggggatcaagcc--agct---
--tatt----tgct-ggg-tgtacttcctgg-t-tgacaggccagcatcag-ttttgacc
atcagagaaaggcc-aagggaatgtggcacc---tttat----aggtgtg---ttatagc
cc-ttggttgtatgt-ggtggttgggactgagg-acagcagcatg-c---ca-ca-t--g
g-c-tgg-----------------g---t--tt-------cgaccacg-ttcatgctttg
gatgttggc---ataatggctttaagc-------
>EF653960_Amanita_curtipes
tcccttagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcagc-g--
----------tttggttgtccgagttgtaacctagagaagtg-cagcctgtgctggacca
tgtataa-gtctcctggaacggagtgtcacagagggtgagaatcccgtgtttgacatgga
c-tg-cc-agtgca-ttgtggc-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaacgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacatttaaagtcagttg-tgt-tagc-tggggatcaacctggggt----
--tatt----gctttggg-tgtatttcctgg-t-tgacaggtcaacatcag-ttctgacc
agtagaaaaagggc-aaggaaatgtggcacc---tt--c----gggtgtg---ttatagt
cc-ttggttgtatct-ggtggttgggactgagg-gatgcagcaca-c---cg-ta-a--g
ggc-cgtggccagatcattcaatgg------gc-------tggcgacg-tttgtgcttat
gatgttggc---ataatggctttaagtgacc---
>AF024485_Amanita_volvata
tcccttagtaact-gcgagtgaagtgggaaaagctcaaatttaaaatct-ggcaacgg--
----------tttggttgtccgagttgtaacctagagaagtg-cagcctgtgctggacca
tgtataa-gtctcctggaatggagtgtcacagagggtgagaatcccgtgtttgacatgga
c-tg-cc-agtgca-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacatttaaagtcagttg-tgt-tagc-tggggatcaacct--ggt----
--ttat----tgcttggg-tgtatttcctgg-g-tgacaggtcaacatcag-ttctgacc
ggtagaaaaaaggc-aaggaaatgtggcacc---tt--t----gggtgtg---ttatagt
cc-ttggctgtatct-agtggttgggactgagg-gatgcagcacacc---ca-ca-a--g
ggc-cgtggccaggtcatt-----g------cc-------tggagacg-tttgtgcttag
gatgttggc---ataatggctttaagtgacccgt
>AF024448_Amanita_clarisquamosa
tcccttagtaact-gcgagtgaagtgggaaaagctcaaatttaaaatct-ggcagc-c--
----------tttggttgtccgagttgtaacctagagaagtg-ctgcctgtgctggacca
tgtataa-gtctcctggaatggagtgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgca-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacatttaaagtcagttg-tgt-tagc-tggggatcaacct--ggt----
--ttat----tgcttggg-tgtatttcctgg-t-tgacaggtcaacatcag-ttttgact
ggtagaaaaaggcc-aaggaaatgtggcacc---tt--t----gggtgtg---ttatagt
cc-ttggttgtatct-ggtggttaggactgagg-tatgcagcaca-c---ca-ca-a--g
ggc-cgtggccaggtcatt-----g------cc-------tggtcacg-tttgtgcttag
gatgt-----------------------------
>AF024487_Amanita_aff_volvata
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-gacagt-ca-
----------tttggttgtccgagttgtaacctagagaagtg-ctgcctgtgttggacca
tgtataa-gtctcctggaatggagtgtcacagagggtgagagtcccgtctttgacatgga
c-tg-cc-aacaca-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ccaaattggtggtaaattccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacatttgaagtcagttg-tgt-cagc-tgggggtcaacct--ggcattc
attttt----tgcttggg-tgtatttcctgg-t-tgacaggtcaacatcag-ttttgacc
actagaaaaaagct-aaggaaatgtggcacc---tt--t----gagtgtg---ttatagt
cc-ttggttgtatgt-ggtggttgggactgagg-tatgcagcaca-c---cg-ca-a--g
g-c-tgg-----------------g---t--tg-------tggccaca-tttgtgcttag
gatgttggc---ataatggctttaagtgacccgt
>AF024441_Amanita_avellaneosquamosa
tcccttagtaact-gcgagtgaagtgggaaaagctcaaatttaaaatct-ggcagc-c--
----------ttaggttgtccgagttgtaacctagagaagtg-ctacctgcactggacca
tgtataa-gtctcctggaatggagtgtcacagagggtgagaatcccgtctttgacatgga
cttg-cc-agtgtg-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacatttgaagtcagttgttgt-tggc-tagggatcaacct--ggct---
--ttct----tgcttggg-tgtatttcctcg-t-taacaggtcaacatcag-ttttgatc
attagaaaaaagcc-aaggaaatgtagcacc---tt-at----gggtgtg---ttatagt
tc-ttggttatatgt-agtgattgggactgagg-catgcagcaca-c---cg-aa-a--g
g-t-tgg-----------------g---a--at-------tggccaca-tttgtgcttag
gatgttgac---ataatggctttaagtgacccgt
>EF653958_Amanita_ponderosa
tcccctagtaact-gcgagtgaagtgggaaaagctcaaatttaaaatct-gacagt-c--
----------tttgactgtctgagttgtaacctagagaagtg-ctacctgtgctggacca
tgtataa-gtctcctggaatggagtgtcagagagggtgagaatcccgtccttgacatgga
c-tg-cc-agtgca-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacatttgaagtcagttg-tgt-tagc-tggggatcaacct--ggct---
--tttc----tgcttggg-tgtatttcctgg-t-tgacaggccaacatcag-ttttgacc
attagaaaaagacc-aaggaaatgtggcacc---tt--t----gggtgtg---ttatagt
cc-ttggttgtatgt-gatggttaggactgagg-catgcagcaca-c---ta-ct-a--g
g-c-tgg-----------------g------ct-------ttgccaca-tttgtgcttag
gatgttggc---ataatggctttaagtgacc---
>AF042608_Amanita_peckiana
tcccctagtaact-gcgagtgaagtgggaaaagctcaaatttaaaatct-gacagt-t--
----------gttgactgtctgagttgtaacctagagaagtg-ctacctgtgctggacca
tgtataa-gtctcctggaatggagtgtcagagagggtgagaatcccgtccttgacatgga
c-tg-cc-agtgta-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtacgtgaaattg
ttgaaagggaaacatttgaagtcagttt-tgt-tagc-tggggatcaacct--ggct---
--tttc----tgcttggg-tgtatttcctgg-t-tgacaggccaacatcag-ttttgacc
attagaaaaagacc-aaggaaatgtggcacc---tt--t----gggtgtg--tttatagt
cc-ttggttgtatgt-ggtggttaggactgagg-catgcagcaca-c---ta-ca-a--g
g-c-tgg-----------------g------nt-------ttgccaca-tttgtgcttag
gatgttggc---ataatggctttaagtgacccgt
>AF097387_Amanita_peckiana
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-gacagt-c--
----------tttgactgtctgagttgtaacctagagaagtg-ctgcccgtgctggacca
tgtataa-gtctcctggaatggagtgtcacagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgca-ttgtggt-gtgctctcaaagagtcgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaggctaaatattggcgagagaccgatagtgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacatttgaagtcagttg-tgt-tagcttggggatcaactc--agct---
--tttc----tgcttggg-tgtatttcctgg-t-tgacaggccaacatcag-ttttgacc
attagaaaaaaacc-aaggaaatgtggcacc---tc--t----gggtgtg---ttatagt
cc-ttggttgtatgt-agtggttgggactgagg-gatgcagcaca-c---ca-ta-a--g
g-c-tgg-----------------g------tt-------ttgccaca-tttgtgcttag
gatgttggc---ataatggctttaagtgacccgt
>FJ011683_Amanita_oberwinklerana
tcccttagtaact-gcgagtgaagtgggaaaagctcaaatttaaaatct-ggcagt-g--
----------tattgctgtccgagttgtagcctagagaagtg-ttaccttcactggaccg
tgtataa-gtctcctgggatggagcatcagagagggtgagaatcccgtgtatgacatgga
c-ta-cc-agtgga-atgtggt-aggctctcaaagagttgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttggagtcagtcg-cgt-tggt-cagggatcaagtc--agtgata
ttattt----tgct-ggg-tgtaatttctgg-a-caacgggccaacatgag-ttttgact
actagagaaaggca-ttgggaatgtggcacc---tg--taagagggtgtg---ttatagg
cc-aaagtcatatag-agtagttgggactgagg-aaagcagcgcg-c---cg-ca-attg
g-c-ggg-----------------g---t--tt-------cgaccacg-ttcgcgcttag
gatgttggc-atataatggctttaagcgacccgt
>AF024471_Amanita_pseudoporphyria
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-gacagt----
----------ttttgctgtccgaattgtagcctagagaagtg-ttgtccgcgccggaccg
tgtataa-gtctcctgggatggagcatcatagagggtgagaatcctgtgtttgacatgga
c-ta-cc-ggtgca-ttgtggc-atgctctcaaagagttgagttgtttgggaatgcagct
ctaaaagggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtcg-cat-tggt-tggggatcagctt--agtt---
--tatt----tgct-gag-tgtaattcctaa-t-ggatgggtcagcatgag-ttttgatc
gctggagaaaggctattgggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-atggttgtatgc-agcggttaggactgagg-aaggcagcgcg-c---cg-ca-a--g
g-a-cgg-----------------g---t--tt-------cgaccacg-ttcgcgcttag
gatgttggc---ataatggctttaagcgacccgt
>AF024463_Amanita_manginiana
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcggt-g--
----------gttagccgtccgaattgtagcctagagaagtg-ttgcctgtgctgaacca
tgtataa-gtctcctgggatggagcgtcagagagggtgagaatcccgtgtttgacatgga
c-ta-gc-agtgca-ttgtggt-acgctctcaaagagttgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtgg-cat-tggg-tggggatcaatgc--agct---
--cttt----tgct-gga-tgtaattcctag-t-cgatgggccaacatgag-ttctgact
gctggagaaaggcg-aggtgaatgtggcact---tt--t----aagtgtg--tttatagc
ac-ctggttgtatgc-agtggttgggactgaggaaaagcagcgcg-c---ca-ct-t--g
g-c-agg-----------------g---t--tt-------cgaccaca-ttcgcgcttag
gatgttggc--aataatggctttaagcgacccgt
>AF024484_Amanita_virgineoides
-cccctagtaaat-ccgagtgaagcgggaaaagctcaaatttaaaatct-ggcagc-g--
----------gttggctgtccgagttgtaacctagagaagtg-ttgcccgtgctggaccg
tgtacaa-gtctcctgggatggagcatcatagagggtgagaatcccgtctctgacaccga
c-ta-cc-agtgca-ctgtggt-atgctctcaaagagttgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtcg-tgt-tggc-cagggatcaaccc--agcta--
--tttt----tggt-ggg-tttacttcctgg-t-caatgggccaacatcag-ttttggtc
actggagaaaggca-ttgggaatgtggcaccctttt--t----gggtgtg---ttatagc
cc-attgtcacatac-agtggctaggactgagg-atagcagcgcg-c---cg-ca-a--g
ggg-cgg-----------------g---t--tt-------cgaccact-tccgcgcttag
gatttgggc---atawkggctttaaccaacccgc
>FJ011682_Amanita_kotohiraensis
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcgga----
-------tttttaggccgtccgagttgtaacctagagaagtg-ttgccagcactggacca
tgtataa-gtctcctgggatggagcgtcagagagggtgagaatcccgtgttggacatgga
t-ta-cc-agagtaattgtggt-atgctctcaaagagttgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttaaagtcagtcg-tgt-tggt-tagggatcaagcc--agta---
--atta----tgct-ggg-tgtagttcctga-t-caatgggtcaacatgag-ttttgact
ggtagagaaaggca-gagagaatgtggcacc---tt--ttc--tggtgtg---ttatagc
tc-tcggtcatatag-atcagttgagactgagg-aaagcagcgtg-c---ca-tt-g--g
g-c-agg-----------------g---t--tt-------cgaccaca-ttcacgcttag
gatgttggc---ataatggctttaagcgacccgt
>FJ011681_Amanita_kotohiraensis
tcccttagtaact-gcgagtgaagagggaaaagctcaaatttaaaatct-ggcggc----
----------attggtcgtccgaattgtaacctagagaagtg-ttacctgaactggacca
tgtacaa-gtctcctgggatggagcgtcagagagggtgagaatcccgtactggacatgga
c-tg-cc-aaggca-ttgtggt-atgctctcaaagagttgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgcttgaagtcagtga-tat-tggt-cagggatcaagcc--agca---
--agtg----tgct-ggg-tgtagtttctgg-a-caatgagtcaacatgag-ttttaact
ggtggagaaaggca-gagggaatgtggcacc---tt--t----gggtgtg---ttatagc
tc-tttgtcatatac-atcaggtgagactgagg-aaagcagcgcg-c---cg-ca-a--g
g-c-agg-----------------g---t--tt-------cgaccacatttcgcgcttag
gatgttggc---ataatggctttaagcgatccgt
>AF024475_Amanita_solitaria
tcccctagtaact-gcgagtgaagcgggataagctcaaatttaaaatct-gatggt-g--
----------tttggccatccgagttgtagcctagagaagtg-ttacccacgctggacca
tgtataa-gtctcctgggatggagcgtcacagagggtgagaatcccgtgtttgacatgga
t-cg-ct-agtgaa-ttgtggt-atgctctcaaagagttgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtca-tgt-tggt-tagggatcaaacc--agcag--
--aaaa----tgct-ggt-tgtagttcctgg-t-caatgggtcaacatcag-ttttgagc
actggagaaagaat-tagggaatgtggcacc---tt--tt---aggtgtg--tttatagc
cc-tgagtcatatac-agtgattgagactgagg-aattcagcgcg-c---cg-ca-a--g
g-c-aga-----------------gtcgt--tt-------cgactaca-ttcgcgcttag
gatgttggc-aaataatggctttaagcgacccgt
>AF024460_Amanita_japonica
tcccctagtaact-gcgagtgaagcgggaagagctcaaatttaaaatct-ggcggt-g--
----------tttggccgtccgagttgtagactagagaagtg-ttacccgaattggacca
tgtataa-gtctcctgggatggagcgtcacagagggtgagaatcccgtgtttgacatgga
t-ca-ct-agttca-ttgtggt-atgctctcaaagagttgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaggctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtcg-tgt-tggt-cagggatcaagcc--agcaa--
--ttgt----tgct-ggg-tgtacttcctgg-g-caatgggccaacatcag-ttctgact
ggtgaagaaaggca-gagggaatgtggcacc---tt--t----tggtgtg---ttatagc
cc-tcggtcatatac-gtcagtcgggactgagg-aacgcagcgcg-c---cg-ca-a--g
g-c-agg-----------------g---t--tt-------cgaccacg-ttcgcgcttag
gatgttggc-aaataatggctttaagcgacccgt
>AY194983_Amanita_conicoverrucosa
tcccctagtaact-gcgagtgaagcgggaaaagctcaaatttaaaatct-ggcggt-c--
----------tttggccgtccgaattgtagcctagagaagtg-ttgcccgcactggacca
tgtataa-gtctcctgggatggagcgtcgcagagggtgagaatcccgtctttgacatgga
c-tg-cc-agtgca-ttgtggt-atgctctcaaagagttgagttgtttgggaatgcagct
ctaaatgggtggtaaattccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtca-tgt-tggt-cagggatcaagcc--agctaa-
--tttt----tgct-ggg-tgtactttctgg-g-caacgggccaacatcag-tttggact
gctggagaaaggcc-tggggaatgtggcacc---ct--ttt--gggtgtg---ttatagc
tc-ttggtcatatac-agcggttgggactgagg-aacgcagcacg-c---cc-ca-a--g
g-c-cgg-----------------g---t--tt-------cgaccacg-ttcgtgcttan
gatgttggc---ttaatggctttaagcnac----
>AF097389_Amanita_solitariiformis
tcccttagtaact-gcgagtgaagagggaatagctcaaatttaaaatct-ggcggt-g--
----------tttggccgtccgaattgtagcctagagaagtg-ttgcccgcgctggacca
tgtataa-gtctcctggaagggagcgtcgcagagggtgagaatcccgtctttgacatgga
c-tg-ccaagtgca-ttgtggtaatgctctcaaagagttgagttgtttgggaatgcagct
ctaaatgggtggtaaactccatctaaagctaaatattggcgagagaccgatagcgaacaa
gtaccgtgagggaaagatgaaaagaactttggaaagagagttaaacagtatgtgaaattg
ttgaaagggaaacgtttgaagtcagtca-cgt-tggt-cagggatcaacct--agctg--
---ttt----tgct-ggg-tgcacttcctggca-caacgggtcaacatcag-ttttgact
gctggagaaaggca-gagggaatgtggcacc---ct--tttgggggtgtg---ttatagc
ccatcggtcatatgc-agtggttgggactgagg-aaagcagtgtg-c---cg-aa-a--a
g-g-ccg-----------------g---g--tcattttggtgaccacgtttcacacttag
gatgttggc-gaataatggctttaagcgacccgt
